# Generated by Django 6.0.4 on 2026-04-27 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
